# Generated by Django 4.2.1 on 2023-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0002_category_news_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания"
            ),
        ),
    ]
